party_codes = {
    100: "Democratic Party",
    200: "Republican Party",
    1: "Federalist Party",
    13: "Democratic-Republican Party",
    22: "Adams Party",
    26: "Anti Masonic Party",
    29: "Whig Party",
    37: "Constitutional Unionist Party",
    44: "Nullifier Party",
    46: "States Rights Party",
    108: "Anti-Lecompton Democrats",
    112: "Conservative Party",
    114: "Readjuster Party",
    117: "Readjuster Democrats",
    203: "Unconditional Unionist Party",
    206: "Unionist Party",
    208: "Liberal Republican Party",
    213: "Progressive Republican Party",
    300: "Free Soil Party",
    310: "American Party",
    326: "National Greenbacker Party",
    340: "Populist PARTY",
    347: "Prohibitionist Party",
    354: "Silver Republican Party",
    355: "Union Labor Party",
    356: "Union Labor Party",
    370: "Progressive Party",
    380: "Socialist Party",
    402: "Liberal Party",
    403: "Law and Order Party",
    522: "American Labor Party",
    523: "American Labor Party (La Guardia)",
    537: "Farmer-Labor Party",
    555: "Jackson Party",
    1060: "Silver Party",
    1111: "Liberty Party",
    1116: "Conservative Republicans",
    1275: "Anti-Jacksonians",
    1346: "Jackson Republican",
    3333: "Opposition Party",
    3334: "Opposition Party (36th)",
    4000: "Anti-Administration Party",
    4444: "Constitutional Unionist Party",
    5000: "Pro-Administration Party",
    6000: "Crawford Federalist Party",
    7000: "Jackson Federalist Party",
    7777: "Crawford Republican Party",
    8000: "Adams-Clay Federalist Party",
    8888: "Adams-Clay Republican Party",
    328: "Independent",
    329: "Independent Democrat",
    331: "Independent Republican",
    603: "Independent Whig"
}

print(party_codes)

